# Generated by Django 4.0.2 on 2022-03-29 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0002_allusers_alter_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
