# Generated by Django 4.0.3 on 2022-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0004_alter_entrystats_entry_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrystats',
            name='entry_date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
