# Generated by Django 4.0.3 on 2022-03-29 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_service', '0005_remove_entry_author_entry_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
