# Generated by Django 4.0.3 on 2022-04-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0006_alter_entrystats_entry_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryStats',
        ),
    ]
