# Generated by Django 4.0.3 on 2022-04-15 06:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_service', '0007_delete_entrystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date_created', models.DateTimeField(auto_now_add=True)),
                ('entry_amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('entry_author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
