# Generated by Django 4.0.3 on 2022-04-15 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_service', '0008_entrystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrystats',
            name='entry_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4096)]),
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
