# Generated by Django 4.0.3 on 2022-04-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0009_alter_entrystats_entry_amount_bloguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
