# Generated by Django 4.0.3 on 2022-04-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0014_alter_userdetails_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_profile_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
