# Generated by Django 4.0.3 on 2022-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0015_userdetails_user_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
