# Generated by Django 4.0.3 on 2022-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0018_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
