version: "3.9"

volumes:
  db_data:
  pgadmin_data:

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - 2237:80
      - 443:443
    depends_on:
      - db
