# Generated by Django 4.0.2 on 2022-03-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='test',
        ),
    ]
