# Generated by Django 4.0.2 on 2022-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0003_allusers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='user_password',
            field=models.CharField(max_length=64),
        ),
    ]
