# Generated by Django 4.0.2 on 2022-03-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0003_entry_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='test',
        ),
    ]
